/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/common/BaseButton.vue')['default']
    BaseInput: typeof import('./components/common/BaseInput.vue')['default']
    FloatingActions: typeof import('./components/common/FloatingActions.vue')['default']
    GlobalHeader: typeof import('./components/common/GlobalHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HelpModal: typeof import('./components/common/HelpModal.vue')['default']
    LanguageModal: typeof import('./components/common/LanguageModal.vue')['default']
    OTPModal: typeof import('./components/common/OTPModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchCard: typeof import('./components/reward/ScratchCard.vue')['default']
  }
}
